-- Create PostgreSQL sequences for ID generation
CREATE SEQUENCE IF NOT EXISTS cat_seq START 10;
CREATE SEQUENCE IF NOT EXISTS com_seq START 10;
CREATE SEQUENCE IF NOT EXISTS opt_seq START 10;
CREATE SEQUENCE IF NOT EXISTS itv_seq START 10;
CREATE SEQUENCE IF NOT EXISTS itc_seq START 10;
CREATE SEQUENCE IF NOT EXISTS loc_seq START 10;
CREATE SEQUENCE IF NOT EXISTS prd_seq START 10;
CREATE SEQUENCE IF NOT EXISTS col_seq START 10;
CREATE SEQUENCE IF NOT EXISTS cpr_seq START 10;
CREATE SEQUENCE IF NOT EXISTS fil_seq START 10;